kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: archestra-ci-cluster
networking:
  # Disable default CNI (kindnet) so we can install Calico for NetworkPolicy enforcement.
  # Without this, Kubernetes NetworkPolicy resources are created but NOT enforced,
  # making SSRF protection via NetworkPolicy ineffective.
  disableDefaultCNI: true
  # Calico's default pod CIDR. This falls within the RFC 1918 range blocked by the
  # SSRF NetworkPolicy, which is intentional — MCP server pods should not reach
  # other pods via IP. Pod-to-pod DNS (port 53) is still allowed.
  podSubnet: "192.168.0.0/16"
nodes:
  - role: control-plane
    extraPortMappings:
      # Map ports for the Archestra platform
      - containerPort: 30000 # Backend API
        hostPort: 9000
        protocol: TCP
      - containerPort: 30050 # Metrics
        hostPort: 9050
        protocol: TCP
      - containerPort: 30300 # Frontend
        hostPort: 3000
        protocol: TCP
      - containerPort: 30080 # WireMock
        hostPort: 8080
        protocol: TCP
      - containerPort: 30081 # Keycloak
        hostPort: 30081
        protocol: TCP
      - containerPort: 30082 # MCP Server JWKS
        hostPort: 30082
        protocol: TCP
      - containerPort: 30200 # Vault
        hostPort: 8200
        protocol: TCP
