allow_k8s_contexts(['orbstack', 'docker-desktop'])

load('ext://helm_remote', 'helm_remote')
load('ext://dotenv', 'dotenv')

# Check if .env exists, if not copy from .env.example
if not os.path.exists('.env'):
  local('cp .env.example .env')
  print("📝 Created .env from .env.example, be sure to fill in any necessary unique values (ex. API keys)")
else:
  print("📝 .env already exists, skipping copy from .env.example")

# PostgreSQL database for local development
# https://dev.to/flodev/use-tilt-to-provide-easy-to-setup-development-environments-4n9d
helm_remote(
  'postgresql',
  repo_url='https://charts.bitnami.com/bitnami',
  namespace='archestra-dev',
  create_namespace=True,
  set=[
    'auth.database=archestra_dev',
    'auth.username=archestra',
    'auth.password=archestra_dev_password',

    # Bitnami is archiving their image.. see this github comment for details
    # https://github.com/coder/coder/issues/19869#issuecomment-3305875979
    # https://github.com/bitnami/containers/issues/83267
    'image.repository=bitnamisecure/postgresql',
    'image.tag=latest',
    'global.security.allowInsecureImages=true'
  ]
)

k8s_resource('postgresql', port_forwards=['5432:5432'], labels=['database'])

dotenv(
  './.env'
)

# pre
local_resource(
  'pnpm-install',
  cmd='pnpm install',
  deps=['./frontend/package.json', './backend/package.json'],
  labels=['pre']
)

local_resource(
  'db-migrate',
  # NOTE: we need to cd into the backend directory to run the migrate command
  # because otherwise if we run the command from this directory, it is run via turbo, which does not properly
  # propogate the required environment variables (ie. DATABASE_URL)
  cmd='cd backend && pnpm db:migrate',
  deps=['./backend/src/database/migrations'],
  resource_deps=['pnpm-install', 'postgresql'],
  labels=['pre']
)

# dev
local_resource(
  'pnpm dev',
  serve_cmd='pnpm dev',
  labels=['dev'],
  resource_deps=['db-migrate']
)

local_resource(
  'database-gui',
  # NOTE: we need to cd into the backend directory to run the migrate command
  # because otherwise if we run the command from this directory, it is run via turbo, which does not properly
  # propogate the required environment variables (ie. DATABASE_URL)
  serve_cmd='cd backend && pnpm db:studio',
  labels=['dev'],
  resource_deps=['db-migrate']
)

local_resource(
  'lint:fix',
  cmd='pnpm type-check && pnpm lint:fix',
  labels=['dev'],
  resource_deps=['pnpm-install'],
  deps=[
    "./frontend/src",
    "./backend/src",
    "./experiments/src",
    "./biome.json"
  ]
)

local_resource(
  'codegen:api-client',
  cmd='pnpm codegen:api-client',
  labels=['dev'],
  resource_deps=['pnpm-install']
)
